/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio35;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 * copiar el archivo mysql-conne&ctor-java-5.1.21-bin en C:\Program Files (x86)\Java\jdk1.7.0_03\jre\lib\ext
 * @author admin
 */
public class Ejercicio35a extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Ejercicio35a() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonleer = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        botonguardar = new javax.swing.JButton();
        combo1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combo2 = new javax.swing.JComboBox();
        botonmodificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonleer.setText("Leer");
        botonleer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonleerActionPerformed(evt);
            }
        });

        botonguardar.setText("Guardar");
        botonguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonguardarActionPerformed(evt);
            }
        });

        combo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo1ItemStateChanged(evt);
            }
        });

        jButton3.setText("Agrega al Combo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        botoneliminar.setText("Eliminar");
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        jLabel2.setText("Apellido");

        jLabel3.setText("DNI");

        jLabel4.setText("Nombre");

        combo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botonmodificar.setText("Modificar");
        botonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmodificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonleer)
                        .addGap(18, 18, 18)
                        .addComponent(botonguardar)
                        .addGap(18, 18, 18)
                        .addComponent(botoneliminar)
                        .addGap(18, 18, 18)
                        .addComponent(botonmodificar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonleer)
                    .addComponent(botonguardar)
                    .addComponent(botoneliminar)
                    .addComponent(botonmodificar))
                .addGap(157, 157, 157))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonleerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonleerActionPerformed

        try 
        {
          Conectar miconexion = new Conectar ();
            String cons = "select * from alumnos";
            ResultSet consulta =miconexion.consulta(cons);
            consulta.next();
            txtid.setText(consulta.getString(1));
            txtnombre.setText(consulta.getString(2));
            txtapellido.setText(consulta.getString(3));
            txtdni.setText(consulta.getString(4));
            
        }
        catch (Exception e)
        {
         JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_botonleerActionPerformed

    private void botonguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonguardarActionPerformed

        try 
        {
         Conectar miconexion = new Conectar ();
         String sentenciaInsert = "insert into alumnos values (?,?,?,?) ";
         
         miconexion.psPrepararSentencias = miconexion.miconexion.prepareStatement(sentenciaInsert);
         miconexion.psPrepararSentencias.setString(1,txtid.getText());
         miconexion.psPrepararSentencias.setString(2,txtnombre.getText());
         miconexion.psPrepararSentencias.setString(3,txtapellido.getText());
         miconexion.psPrepararSentencias.setString(4,txtdni.getText());
         miconexion.psPrepararSentencias.executeUpdate();
        }
        catch (Exception e)
             {
              JOptionPane.showMessageDialog(null, e.getCause());
             }
        
        
    }//GEN-LAST:event_botonguardarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try
        {
            
        
         combo1.removeAllItems();
            Conectar miconexion = new Conectar ();
            String cons = "select id from alumnos";
            ResultSet consulta =miconexion.consulta(cons);
            consulta.next();
            
            for (int i=0;i<consulta.getRow();i++)
            {
                     combo1.addItem(consulta.getString(1));
                     consulta.next();
            }        
        }
              catch (Exception e)
             {
              JOptionPane.showMessageDialog(null, e.getCause());
             }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed

         try 
        {
         Conectar miconexion = new Conectar ();
         String sentenciaDelete = "delete from alumnos where id = ? ";
         
         miconexion.psPrepararSentencias = miconexion.miconexion.prepareStatement(sentenciaDelete);
         miconexion.psPrepararSentencias.setString(1,txtid.getText());
         miconexion.psPrepararSentencias.executeUpdate();
        }
        catch (Exception e)
             {
              JOptionPane.showMessageDialog(null, e.getCause());
             }
        
        
        
        
    }//GEN-LAST:event_botoneliminarActionPerformed

    private void combo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo1ItemStateChanged
      
         try 
        {
            combo2.removeAllItems();
          Conectar miconexion = new Conectar ();
            String cons = "select nombre from alumnos where id = " + combo1.getSelectedItem();
            ResultSet consulta =miconexion.consulta(cons);
            consulta.next();
         
         for (int i=0;i<consulta.getRow();i++)
            {
                     combo2.addItem(consulta.getString(1));
                     consulta.next();
            }        
       // consulta.close();
         
        }
        catch (Exception e)
        {
         JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_combo1ItemStateChanged

    private void botonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmodificarActionPerformed

        try 
        {
         Conectar miconexion = new Conectar ();
         String modificar = "update alumnos set nombre=(?),apellido=(?),dni=(?) "+"where id="+txtid.getText();
         
         miconexion.psPrepararSentencias = miconexion.miconexion.prepareStatement(modificar);
         miconexion.psPrepararSentencias.setString(1,txtnombre.getText());
         miconexion.psPrepararSentencias.setString(2,txtapellido.getText());
         miconexion.psPrepararSentencias.setString(3,txtdni.getText());
         miconexion.psPrepararSentencias.executeUpdate();
        }
        catch (Exception e)
             {
              JOptionPane.showMessageDialog(null, e.getCause());
             }
        // TODO add your handling code here:
    }//GEN-LAST:event_botonmodificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio35a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio35a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio35a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio35a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ejercicio35a().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoneliminar;
    private javax.swing.JButton botonguardar;
    private javax.swing.JButton botonleer;
    private javax.swing.JButton botonmodificar;
    private javax.swing.JComboBox combo1;
    private javax.swing.JComboBox combo2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
