/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mamenor2;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author emi
 */
public class mm2 extends javax.swing.JFrame {
    int val1,val2,val3;
    public int calcular_mayor(int v1,int v2,int v3){
        int mayor;
        mayor=v1;
        if(v2>mayor)
            mayor=v2;
        if(v3>mayor)
            mayor=v3;
        return mayor;
            
}
    public int calcular_menor(int v1,int v2,int v3){
        int menor;
        menor=v1;
        if(menor>v2)
            menor=v2;
        if(menor>v3)
            menor=v3;
        return menor;
    }
    /**
     * Creates new form mm2
     */
    public mm2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caja1 = new javax.swing.JTextField();
        caja2 = new javax.swing.JTextField();
        caja3 = new javax.swing.JTextField();
        bmayor = new javax.swing.JButton();
        bmenor = new javax.swing.JButton();
        etres = new javax.swing.JLabel();
        bsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        caja1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja1KeyPressed(evt);
            }
        });

        caja2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja2KeyPressed(evt);
            }
        });

        bmayor.setText("Mayor");
        bmayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmayorActionPerformed(evt);
            }
        });

        bmenor.setText("Menor");
        bmenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmenorActionPerformed(evt);
            }
        });

        etres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bsalir.setText("Salir");
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etres, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(caja3, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addComponent(caja2)
                        .addComponent(caja1)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bmayor)
                    .addComponent(bmenor))
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(caja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(caja3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bmayor)
                        .addGap(18, 18, 18)
                        .addComponent(bmenor)
                        .addGap(45, 45, 45)))
                .addComponent(etres, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bsalir)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bmayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmayorActionPerformed
val1= Integer.parseInt(caja1.getText());
val2= Integer.parseInt(caja2.getText());
val3= Integer.parseInt(caja3.getText());
etres.setForeground(Color.GREEN);
etres.setText("El numero mayor ingresado es el: "+calcular_mayor(val1,val2,val3));

// TODO add your handling code here:
    }//GEN-LAST:event_bmayorActionPerformed

    private void bmenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmenorActionPerformed
val1= Integer.parseInt(caja1.getText());
val2= Integer.parseInt(caja2.getText());
val3= Integer.parseInt(caja3.getText());
etres.setForeground(Color.RED);
etres.setText("El numero menor ingresado es el: "+calcular_menor(val1,val2,val3));        // TODO add your handling code here:
    }//GEN-LAST:event_bmenorActionPerformed

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_bsalirActionPerformed

    private void caja1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja1KeyPressed
if(evt.getKeyCode()==KeyEvent.VK_TAB)
    caja2.grabFocus();// TODO add your handling code here:
    }//GEN-LAST:event_caja1KeyPressed

    private void caja2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja2KeyPressed
    if(evt.getKeyCode()==KeyEvent.VK_TAB)
    caja3.grabFocus();    // TODO add your handling code here:
    }//GEN-LAST:event_caja2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new mm2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bmayor;
    private javax.swing.JButton bmenor;
    private javax.swing.JButton bsalir;
    private javax.swing.JTextField caja1;
    private javax.swing.JTextField caja2;
    private javax.swing.JTextField caja3;
    private javax.swing.JLabel etres;
    // End of variables declaration//GEN-END:variables
}
