/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ejer1;

import java.awt.Color;

/**
 *
 * @author emi
 */
public class Ejer1visual extends javax.swing.JFrame {
int val1,val2,val3;
    public int mayor(int v1,int v2,int v3){
        int mayor;
        mayor=v1;
        if(v2>mayor)
            mayor=v2;
        if(v3>mayor)
            mayor=v3;
        return mayor;
            
}
    public int menor(int v1,int v2,int v3){
        int menor;
        menor=v1;
        if(menor>v2)
            menor=v2;
        if(menor>v3)
            menor=v3;
        return menor;
    }
   
      
    /**
     * Creates new form Ejer1visual
     */
    public Ejer1visual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bmax = new javax.swing.JButton();
        bmed = new javax.swing.JButton();
        bmin = new javax.swing.JButton();
        etres = new javax.swing.JLabel();
        caja1 = new javax.swing.JTextField();
        caja2 = new javax.swing.JTextField();
        caja3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bmax.setText("Max");
        bmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmaxActionPerformed(evt);
            }
        });

        bmed.setText("Med");
        bmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmedActionPerformed(evt);
            }
        });

        bmin.setText("Min");
        bmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bminActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(caja1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(caja2)
                            .addComponent(caja3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bmax, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(bmed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(etres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bmax)
                    .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bmed)
                    .addComponent(caja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bmin)
                    .addComponent(caja3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(etres, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmaxActionPerformed
val1= Integer.parseInt(caja1.getText());
val2= Integer.parseInt(caja2.getText());
val3= Integer.parseInt(caja3.getText());
etres.setForeground(Color.GREEN);
etres.setText("El numero mayor ingresado es el: "+mayor(val1,val2,val3));      
        // TODO add your handling code here:
    }//GEN-LAST:event_bmaxActionPerformed

    private void bminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bminActionPerformed
      val1= Integer.parseInt(caja1.getText());
val2= Integer.parseInt(caja2.getText());
val3= Integer.parseInt(caja3.getText());
etres.setForeground(Color.RED);
etres.setText("El numero mayor ingresado es el: "+menor(val1,val2,val3));  // TODO add your handling code here:
    }//GEN-LAST:event_bminActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmedActionPerformed
 val1= Integer.parseInt(caja1.getText());
val2= Integer.parseInt(caja2.getText());
val3= Integer.parseInt(caja3.getText());

//res=a+b+c-max-min muy buena

if(val1>val2 && val1>val3)
        {
        if(val2>val3)
        {etres.setForeground(Color.BLUE);
           etres.setText("El numero medio ingresado es el: "+ val2);} 
        else
        {etres.setForeground(Color.BLUE);
           etres.setText("El numero medio ingresado es el: "+ val3);}    
        }
if(val2>val1 && val2>val3)
        {
        if(val1>val3)
        {etres.setForeground(Color.BLUE);
           etres.setText("El numero medio ingresado es el: "+ val1);} 
        else
        {etres.setForeground(Color.BLUE);
           etres.setText("El numero medio ingresado es el: "+ val3);}    
        }
if(val3>val2 && val3>val1)
        {
        if(val2>val1)
        {etres.setForeground(Color.BLUE);
           etres.setText("El numero medio ingresado es el: "+ val2);} 
        else
        {etres.setForeground(Color.BLUE);
           etres.setText("El numero medio ingresado es el: "+ val1);}    
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_bmedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejer1visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejer1visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejer1visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejer1visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ejer1visual().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bmax;
    private javax.swing.JButton bmed;
    private javax.swing.JButton bmin;
    private javax.swing.JTextField caja1;
    private javax.swing.JTextField caja2;
    private javax.swing.JTextField caja3;
    private javax.swing.JLabel etres;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
