/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ejer2;

/**
 *
 * @author emi
 */
public class Ejer2visual extends javax.swing.JFrame {
int val1,val2;
int oper=0;
public int suma (int v1,int v2){
return v1 + v2;
}
public int multi (int v1,int v2){
return v1 * v2;
}
public int divi (int v1,int v2){
return v1 / v2;
}
public int resta (int v1,int v2){
return v1 - v2;
}
    /**
     * Creates new form Ejer2visual
     */
    public Ejer2visual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bsuma = new javax.swing.JButton();
        bresta = new javax.swing.JButton();
        bmulti = new javax.swing.JButton();
        bdivi = new javax.swing.JButton();
        bres = new javax.swing.JButton();
        etalerta = new javax.swing.JLabel();
        caja1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bsuma.setText("+");
        bsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsumaActionPerformed(evt);
            }
        });

        bresta.setText("-");
        bresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brestaActionPerformed(evt);
            }
        });

        bmulti.setText("*");
        bmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmultiActionPerformed(evt);
            }
        });

        bdivi.setText("/");
        bdivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdiviActionPerformed(evt);
            }
        });

        bres.setText("=");
        bres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresActionPerformed(evt);
            }
        });

        etalerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        caja1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        caja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bres, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bsuma)
                                    .addComponent(bmulti))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bresta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bdivi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etalerta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsuma)
                    .addComponent(bresta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bmulti)
                    .addComponent(bdivi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etalerta, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresActionPerformed
    val2=Integer.parseInt(caja1.getText());
    if(val2 > 9 && val2 < 100)
        switch(oper)
            {
                case 1: caja1.setText(""+suma(val1,val2));break;
                case 2: caja1.setText(""+resta(val1,val2));break;
                case 3: caja1.setText(""+multi(val1,val2));break;
                case 4: caja1.setText(""+divi(val1,val2));break;
                default: break;    
            }
    else
        {etalerta.setText("Solo numero de 2 cifras");
        caja1.setText("");}
        // TODO add your handling code here:
    }//GEN-LAST:event_bresActionPerformed

    private void bsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsumaActionPerformed
val1=Integer.parseInt(caja1.getText());
if(val1 > 9 && val1 < 100)
{ oper=1;
    caja1.setText("");caja1.grabFocus();etalerta.setText("");}
else
{etalerta.setText("Solo numero de 2 cifras");
    caja1.setText("");}
    // TODO add your handling code here:
    }//GEN-LAST:event_bsumaActionPerformed

    private void brestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brestaActionPerformed
val1=Integer.parseInt(caja1.getText());
if(val1 > 9 && val1 < 100)
{ oper=2;
    caja1.setText("");caja1.grabFocus();etalerta.setText("");}
else
{etalerta.setText("Solo numero de 2 cifras");
    caja1.setText("");}        // TODO add your handling code here:
    }//GEN-LAST:event_brestaActionPerformed

    private void bmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmultiActionPerformed
val1=Integer.parseInt(caja1.getText());
if(val1 > 9 && val1 < 100)
{ oper=3;
    caja1.setText("");caja1.grabFocus();etalerta.setText("");}
else
{etalerta.setText("Solo numero de 2 cifras");
    caja1.setText("");}       // TODO add your handling code here:
    }//GEN-LAST:event_bmultiActionPerformed

    private void bdiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdiviActionPerformed
val1=Integer.parseInt(caja1.getText());
if(val1 > 9 && val1 < 100)
{ oper=4;
    caja1.setText("");caja1.grabFocus();etalerta.setText("");}
else
{etalerta.setText("Solo numero de 2 cifras");
    caja1.setText("");}       // TODO add your handling code here:
    }//GEN-LAST:event_bdiviActionPerformed

    private void caja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejer2visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejer2visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejer2visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejer2visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ejer2visual().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdivi;
    private javax.swing.JButton bmulti;
    private javax.swing.JButton bres;
    private javax.swing.JButton bresta;
    private javax.swing.JButton bsuma;
    private javax.swing.JTextField caja1;
    private javax.swing.JLabel etalerta;
    // End of variables declaration//GEN-END:variables
}
