/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * abmarticulos.java
 *
 * Created on 30-oct-2012, 21:17:48
 */
package menu;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pepo
 */
public class abmarticulos extends javax.swing.JDialog {
    DefaultTableModel objtabla = new DefaultTableModel();
libreria metodos = new libreria();

    /** Creates new form abmarticulos */
    public abmarticulos(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
         String titulos [] = {"Nombre","Precio","Cantidad"};
        objtabla.setColumnIdentifiers(titulos);
        tabla.setModel(objtabla);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try
{
    Conectar miconexion = new Conectar ();
    String cons = "SELECT productos.nombre,productos.precio, stock.cantidad FROM productos INNER JOIN stock ON stock.id_prod = productos.id_prod order by productos.nombre";
    ResultSet consulta = miconexion.consulta(cons);
    consulta.next();
    tabla.setModel(objtabla);
    String datos[] = new String[3];
    for (int i=0;i<consulta.getRow();i++)
    {
        for (int j=0;j<3;j++)
        {
            datos [j] = consulta.getString(j+1);
        }
        objtabla.addRow(datos);
        consulta.next();
    }
}

catch (Exception e)
{
    JOptionPane.showMessageDialog(null, e.getMessage());
}// TODO add your handling code here:
}//GEN-LAST:event_formWindowOpened

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
articulos a=new articulos(new javax.swing.JDialog(),true);
        a.setVisible(true);
        
        objtabla.getDataVector().clear();
         tabla.repaint();
         tabla.revalidate();
         
        try
{
    Conectar miconexion = new Conectar ();
    String cons = "SELECT productos.nombre,productos.precio, stock.cantidad FROM productos INNER JOIN stock ON stock.id_prod = productos.id_prod order by productos.nombre";
    ResultSet consulta = miconexion.consulta(cons);
    consulta.next();
    tabla.setModel(objtabla);
    String datos[] = new String[3];
    for (int i=0;i<consulta.getRow();i++)
    {
        for (int j=0;j<3;j++)
        {
            datos [j] = consulta.getString(j+1);
        }
        objtabla.addRow(datos);
        consulta.next();
    }
}

catch (Exception e)
{
 JOptionPane.showMessageDialog(null, e.getMessage());
}       // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      int valor=0;
     
try
{
    



/*valor=Integer.parseInt(consulta.getString(2));
valor=valor+Integer.parseInt(textcantidad.getText()); 
//String insertar = "update productos set cantidad = (?) where nombre = " + "'"+ textproducto.getText()+ "'"; 
String modificar = "update stock set cantidad = (?) where id_prod = "+ consulta.getString(1) ;
miconexion.psPrepararSentencias=miconexion.miconexion.prepareStatement(modificar);

miconexion.psPrepararSentencias.setString(1,String.valueOf(valor)); 
miconexion.psPrepararSentencias.executeUpdate();
JOptionPane.showMessageDialog(null, "Grabado");*/
}

catch (Exception e)
{
    JOptionPane.showMessageDialog(null, e.getMessage());
}// TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int fila;
        fila = tabla.getSelectedRow();
        if (fila >= 0) {
            objtabla.removeRow(fila);
            try
            {
                Conectar miconexion = new Conectar ();
                String eliminar = "";
            }
           catch (Exception e)
{
    JOptionPane.showMessageDialog(null, e.getMessage());
}
        }
            // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(abmarticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(abmarticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(abmarticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(abmarticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                abmarticulos dialog = new abmarticulos(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
