/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cargastock.java
 *
 * Created on 27-sep-2012, 21:17:18
 */
package menu;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Pepo
 */
public class cargastock extends javax.swing.JDialog {

    /** Creates new form cargastock */
    public cargastock(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textproducto = new javax.swing.JTextField();
        textcantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Cantidad");

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ver todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(textcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int valor=0;
     
try
{
    

Conectar miconexion = new Conectar (); 
//String cons = "select cantidad from stock where nombre = " + "'"+ textproducto.getText()+ "'";
String cons = "select productos.id_prod, stock.cantidad from productos inner join stock on stock.id_prod = productos.id_prod where productos.nombre = " + "'" + textproducto.getText()+ "'";
ResultSet consulta =miconexion.consulta(cons);



if (consulta.next())
{
valor=Integer.parseInt(consulta.getString(2));
valor=valor+Integer.parseInt(textcantidad.getText()); 
//String insertar = "update productos set cantidad = (?) where nombre = " + "'"+ textproducto.getText()+ "'"; 
String modificar = "update stock set cantidad = (?) where id_prod = "+ consulta.getString(1) ;
miconexion.psPrepararSentencias=miconexion.miconexion.prepareStatement(modificar);

miconexion.psPrepararSentencias.setString(1,String.valueOf(valor)); 
miconexion.psPrepararSentencias.executeUpdate();
JOptionPane.showMessageDialog(null, "Grabado");
}
else
{
    String valorid = "0"; 
    int valor1 = 0;
    String consid = "select id_prod from productos order by id_prod";
    ResultSet consultaid =miconexion.consulta(consid);
          if (consultaid.first())
            
            {
               consultaid.last();
                valorid = consultaid.getString(1);//.toString();            
            
            }
            
           valor1 = Integer.parseInt(valorid); 
           consultaid.close();
          
         String sentenciaInsert = "insert into productos values (?,?)";
         miconexion.psPrepararSentencias = miconexion.miconexion.prepareStatement(sentenciaInsert);
         miconexion.psPrepararSentencias.setString(1,""+(valor1+1));
         miconexion.psPrepararSentencias.setString(2,textproducto.getText());
         
         miconexion.psPrepararSentencias.executeUpdate();
         
         
         String sentenciaInsert2 = "insert into stock values (?,?)";
         miconexion.psPrepararSentencias = miconexion.miconexion.prepareStatement(sentenciaInsert2);
         miconexion.psPrepararSentencias.setString(1,""+(valor1+1));
         miconexion.psPrepararSentencias.setString(2,textcantidad.getText());
         miconexion.psPrepararSentencias.executeUpdate();
         JOptionPane.showMessageDialog(null,"Grabado!");
}
}

catch (Exception e)

{
JOptionPane.showMessageDialog(null, e.getMessage());

}

textproducto.setText(""); 
textcantidad.setText("");
textproducto.grabFocus();
    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
muestraart d=new muestraart(new javax.swing.JDialog(),true);
        d.setVisible(true);
        
        textproducto.setText(d.metodos.nombre);
        textcantidad.grabFocus();
        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    try
{
 int ultimo = 0;
  Conectar miconexion = new Conectar (); 
  String cons = "select max(id_prod) from productos";
  
  ResultSet consulta =miconexion.consulta(cons);
  consulta.next();
  String id = consulta.getString(1);
  
  //ultimo = Integer.parseInt();
  //textid.setText(ultimo);
}

catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    // TODO add your handling code here:
}//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cargastock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cargastock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cargastock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cargastock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                cargastock dialog = new cargastock(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textcantidad;
    private javax.swing.JTextField textproducto;
    // End of variables declaration//GEN-END:variables
}
