/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * comprastock.java
 *
 * Created on 26-sep-2012, 14:59:30
 */
package menu;

import com.mysql.jdbc.ResultSetMetaData;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pepo
 */
public class comprastock extends javax.swing.JDialog {
DefaultTableModel objtabla = new DefaultTableModel();

    /** Creates new form comprastock */
    public comprastock(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String Titulos []= {"Detalle","Cantidad"};
        objtabla.setColumnIdentifiers(Titulos);
        tabla1.setModel(objtabla);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textprod = new javax.swing.JTextField();
        textcant = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Producto :");

        jLabel2.setText("Cantidad :");

        textprod.setEditable(false);
        textprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textprodKeyReleased(evt);
            }
        });

        jButton1.setText("Cargar Stock");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla1);

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textprod, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5))
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textcant, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jButton2)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
      int valor=0;
     
try
{
    

Conectar miconexion = new Conectar (); 
//String cons = "select cantidad from stock where nombre = " + "'"+ textproducto.getText()+ "'";
for(int i=0;i<objtabla.getRowCount();i++)
{
String cons = "select productos.id_prod, stock.cantidad from productos inner join stock on stock.id_prod = productos.id_prod where productos.nombre = " + "'" + tabla1.getValueAt(i,0).toString() + "'";
ResultSet consulta =miconexion.consulta(cons);



if (consulta.next())
{
valor=Integer.parseInt(consulta.getString(2));
valor=valor+Integer.parseInt(tabla1.getValueAt(i,1).toString()); 
//String insertar = "update productos set cantidad = (?) where nombre = " + "'"+ textproducto.getText()+ "'"; 


String modificar = "update stock set cantidad = (?) where id_prod = "+ consulta.getString(1) ;
miconexion.psPrepararSentencias=miconexion.miconexion.prepareStatement(modificar);
miconexion.psPrepararSentencias.setString(1,String.valueOf(valor)); 
miconexion.psPrepararSentencias.executeUpdate();

}
else
{
    JOptionPane.showMessageDialog(null, "No existe el articulo");
 }
}
JOptionPane.showMessageDialog(null, "Grabado");
}

catch (Exception e)

{
JOptionPane.showMessageDialog(null, e.getMessage());

}

textprod.setText(""); 
textcant.setText("");
textprod.grabFocus();
objtabla.getDataVector().clear();
         tabla1.repaint();
         tabla1.revalidate();
         // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void textprodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textprodKeyReleased
      //
  /// TODO add your handling code here:
}//GEN-LAST:event_textprodKeyReleased

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
muestraart d=new muestraart(new javax.swing.JDialog(),true);
        d.setVisible(true);
        
        textprod.setText(d.metodos.nombre);
        textcant.grabFocus();
// TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  double cant=0, precio=0,subtot=0;
        String datos[] = new String[2];
        datos[1] = (String) textcant.getText();
        datos[0] = textprod.getText();
        //datos[2] = textprecio.getText();
       // cant= Double.parseDouble(textcant.getText());
       // precio =   Double.parseDouble(textprecio.getText());
       // subtot = cant*precio;
        //datos[3] =  String.valueOf(subtot);
       
        objtabla.addRow(datos);
        
        textprod.setText("");
        textcant.setText("");
        //textprecio.setText("");
        
        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  
    try
    {
        Conectar miconexion = new Conectar (); 
        
    String valorid = "0"; 
    int valor1 = 0;
    String consid = "select id_prod from productos order by id_prod";
    ResultSet consultaid =miconexion.consulta(consid);
          if (consultaid.first())
            
            {
               consultaid.last();
                valorid = consultaid.getString(1);//.toString();            
            
            }
            
           valor1 = Integer.parseInt(valorid)+1; 
           
           textprod.grabFocus();
           consultaid.close();
    }
    
   catch (Exception e)

{
JOptionPane.showMessageDialog(null, e.getMessage());

}
           // TODO add your handling code here:
}//GEN-LAST:event_formWindowOpened

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int fila;
        fila = tabla1.getSelectedRow();
        if (fila >= 0) {
            objtabla.removeRow(fila);
        }
           // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comprastock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comprastock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comprastock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comprastock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                comprastock dialog = new comprastock(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField textcant;
    private javax.swing.JTextField textprod;
    // End of variables declaration//GEN-END:variables
}
