/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * venta.java
 *
 * Created on 28-sep-2012, 0:49:51
 */
package menu;

import java.awt.Color;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pepo
 */
public class venta extends javax.swing.JDialog {
libreria metodos = new libreria();
     DefaultTableModel objtabla = new DefaultTableModel();
    /** Creates new form venta */
    public venta(javax.swing.JDialog parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        String Titulos []= {"Cantidad","Detalle","Precio","Subtotal"};
        objtabla.setColumnIdentifiers(Titulos);
        tabla.setModel(objtabla);
     
        
     Calendar cal=Calendar.getInstance();
     int dd=cal.get(cal.DATE);
     int mm=cal.get(cal.MONTH)+1;
     int aaaa=cal.get(cal.YEAR);
     labelfecha.setText(aaaa+"-"+mm+"-"+dd);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textproducto = new javax.swing.JTextField();
        textcantidad = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelfecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        textprecio = new javax.swing.JTextField();
        texttotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        comboclientes = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Detalle");

        jLabel2.setText("Cantidad");

        jButton1.setText("Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textproducto.setEditable(false);

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Cliente");

        jLabel5.setText("Fecha");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton3.setText("Agregar a la lista");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setText("Precio :");

        textprecio.setEditable(false);

        jLabel13.setText("Total");

        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        comboclientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(textprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(comboclientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(textproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))
                                    .addComponent(jButton3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(texttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(415, 415, 415))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboclientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(textprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(17, 17, 17)
                        .addComponent(jButton1))
                    .addComponent(jButton4))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
      int valor=0;
     
try
{
    

Conectar miconexion = new Conectar (); 
//String cons = "select cantidad from stock where nombre = " + "'"+ textproducto.getText()+ "'";
for (int i=0;i<objtabla.getRowCount();i++)
{
String cons = "select productos.id_prod, stock.cantidad from productos inner join stock on stock.id_prod = productos.id_prod where productos.nombre = " + "'" + tabla.getValueAt(i,1).toString() + "'";
ResultSet consulta =miconexion.consulta(cons);



if (consulta.next())
{
valor=Integer.parseInt(consulta.getString(2));
valor=valor-Integer.parseInt(tabla.getValueAt(i,0).toString()); 
//String insertar = "update productos set cantidad = (?) where nombre = " + "'"+ textproducto.getText()+ "'"; 


String modificar = "update stock set cantidad = (?) where id_prod = "+ consulta.getString(1) ;
miconexion.psPrepararSentencias=miconexion.miconexion.prepareStatement(modificar);
miconexion.psPrepararSentencias.setString(1,String.valueOf(valor)); 
miconexion.psPrepararSentencias.executeUpdate();

}

  
}

}

catch (Exception e)
{
JOptionPane.showMessageDialog(null, e.getMessage());

}



try
    {
        Conectar miconexion = new Conectar (); 
        
    String valorid = "0"; 
    int valor1 = 0;

           
    String consid = "select id_remito from detalle order by id_remito";
    ResultSet consultaid =miconexion.consulta(consid);
          if (consultaid.first())
            
            {
                  
                consultaid.last();
                valorid = consultaid.getString(1);
                
                valor1 = Integer.parseInt(valorid)+1; 
             //   for (int i=0; i<tabla.getRowCount();i++)
               
                 for (int i=0; i<tabla.getRowCount();i++)
            {
                  
             String sentenciaInsert = "insert into detalle values (?,?,?,?,?) ";
             miconexion.psPrepararSentencias = miconexion.miconexion.prepareStatement(sentenciaInsert);
             miconexion.psPrepararSentencias.setString(1,""+valor1);
             miconexion.psPrepararSentencias.setString(2,tabla.getValueAt(i, 0).toString());
             miconexion.psPrepararSentencias.setString(3,tabla.getValueAt(i, 1).toString());
             miconexion.psPrepararSentencias.setString(4,tabla.getValueAt(i, 2).toString());
             miconexion.psPrepararSentencias.setString(5,tabla.getValueAt(i, 3).toString());
             miconexion.psPrepararSentencias.executeUpdate();
            }
               
                //.toString();            
            
            }
            JOptionPane.showMessageDialog(null, "Grabado");
           textproducto.setText(""); 
textcantidad.setText("");
textproducto.grabFocus();
objtabla.getDataVector().clear();
         tabla.repaint();
         tabla.revalidate();
textproducto.grabFocus();
           textproducto.grabFocus();
           consultaid.close();
    }
    
   catch (Exception e)

{
JOptionPane.showMessageDialog(null, e.getMessage());

}

// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int bandera=1;
    if (metodos.validarnumeros(textcantidad.getText())==false)
 {
     
     textcantidad.setForeground(Color.BLUE);
             bandera=1;
 }
 else
 {
     textcantidad.setForeground(Color.red);
     bandera = 0;
 }
     
     if (metodos.validarnumeros(textproducto.getText())==true)
     {
         
         textproducto.setForeground(Color.BLUE);
         
     }    
     else
     {
         textproducto.setForeground(Color.red);
         bandera = 0;
     }
         if (metodos.validarnumeros(textprecio.getText())==false)
         {
             
             textprecio.setForeground(Color.BLUE);
             
             
         }    
         else
         {
             textprecio.setForeground(Color.red);
             bandera = 0;
         }
         
        
             
             if (bandera !=0)
             {
    int valor=0;
     
try
{
    

Conectar miconexion = new Conectar (); 

String cons = "select productos.id_prod, stock.cantidad from productos inner join stock on stock.id_prod = productos.id_prod where productos.nombre = " + "'" + textproducto.getText()+ "'";
ResultSet consulta =miconexion.consulta(cons);


if (consulta.next())
{
valor=Integer.parseInt(consulta.getString(2));
if(Integer.parseInt(consulta.getString(2)) < Integer.parseInt(textcantidad.getText()))
{
    JOptionPane.showMessageDialog(null, "No hay esa cantidad en stock");
    textcantidad.setText("");
    textprecio.setText("");
    textcantidad.grabFocus();
}
else
{   
    double cant=0, precio=0,subtot=0;
        String datos[] = new String[4];
        datos[0] = (String) textcantidad.getText();
        datos[1] = textproducto.getText();
        datos[2] = textprecio.getText();
        cant= Double.parseDouble(textcantidad.getText());
        precio =   Double.parseDouble(textprecio.getText());
        subtot = cant*precio;
        datos[3] =  String.valueOf(subtot);
       
        objtabla.addRow(datos);
        texttotal.setText("");
        texttotal.setText("" + metodos.resultado(objtabla));
        textcantidad.setText("");
        textproducto.setText("");
        textprecio.setText("");
        textproducto.grabFocus();
        }
}
        }
 catch (Exception e)
             {
              JOptionPane.showMessageDialog(null, e.getCause());
             }
             }        // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
muestraart d=new muestraart(new javax.swing.JDialog(),true);
        d.setVisible(true);        
        textproducto.setText(d.metodos.nombre);
        try
        {
            String valor = "0";
            Conectar miconexion = new Conectar ();
            String select = "select productos.precio from productos where nombre = '"+ textproducto.getText()+ "'";
            
            ResultSet consulta =miconexion.consulta(select);
            consulta.next();
            valor = consulta.getString(1);
            textprecio.setText(""+valor);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        textcantidad.grabFocus();
        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int fila;
        fila = tabla.getSelectedRow();
        if (fila >= 0) {
            objtabla.removeRow(fila);
            texttotal.setText("");
           texttotal.setText("" + metodos.resultado(objtabla));
            
           // txtcanttot.setText(""+ metodos.cant(objtabla));
        }// TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try
    {
        Conectar miconexion = new Conectar (); 
        
    String valorid = "0"; 
    int valor1 = 0;
    String consid = "select id_remito from detalle order by id_remito";
    ResultSet consultaid =miconexion.consulta(consid);
          if (consultaid.first())
            
            {
               consultaid.last();
                valorid = consultaid.getString(1);//.toString();            
            
            }
            
           valor1 = Integer.parseInt(valorid)+1; 
           
           String insertar = "insert into detalle values (?)";
           miconexion.psPrepararSentencias = miconexion.miconexion.prepareStatement(insertar);
           
           
           consultaid.close();
    }
    
   catch (Exception e)

{
JOptionPane.showMessageDialog(null, e.getMessage());

}
String cons = "SELECT clientes.id_cliente, clientes.nombre FROM clientes";
comboclientes = metodos.cargarcombo(comboclientes, cons);

// TODO add your handling code here:
}//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                venta dialog = new venta(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboclientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelfecha;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField textcantidad;
    private javax.swing.JTextField textprecio;
    private javax.swing.JTextField textproducto;
    private javax.swing.JTextField texttotal;
    // End of variables declaration//GEN-END:variables
}
